aws-controllers-k8s/rds-controller

- helm/Chart.yaml
- helm/crds/rds.services.k8s.aws_dbinstances.yaml
- helm/crds/rds.services.k8s.aws_dbparametergroups.yaml
- helm/crds/rds.services.k8s.aws_dbsecuritygroups.yaml
- helm/crds/rds.services.k8s.aws_dbsubnetgroups.yaml
- helm/crds/services.k8s.aws_adoptedresources.yaml
- helm/templates/_helpers.tpl
- helm/templates/cluster-role-binding.yaml
- helm/templates/cluster-role-controller.yaml
- helm/templates/deployment.yaml
- helm/templates/role-reader.yaml
- helm/templates/role-writer.yaml
- helm/templates/service-account.yaml
- helm/values.yaml
aws-controllers-k8s/community#754
> release artifacts for release v0.0.1

- helm/Chart.yaml
- helm/crds/rds.services.k8s.aws_dbinstances.yaml
- helm/crds/rds.services.k8s.aws_dbparametergroups.yaml
- helm/crds/rds.services.k8s.aws_dbsecuritygroups.yaml
- helm/crds/rds.services.k8s.aws_dbsubnetgroups.yaml
- helm/templates/cluster-role-controller.yaml
- helm/templates/deployment.yaml
- helm/templates/role-reader.yaml
- helm/templates/role-writer.yaml
- helm/values.yaml
release artifacts for RDS controller v0.0.2 with support for DBCluster resources.
aws-controllers-k8s/community#626
> release artifacts for release v0.0.2

- helm/Chart.yaml
- helm/crds/rds.services.k8s.aws_dbclusterparametergroups.yaml
- helm/crds/rds.services.k8s.aws_dbclusters.yaml
- helm/crds/services.k8s.aws_adoptedresources.yaml
- helm/templates/cluster-role-controller.yaml
- helm/templates/metrics-service.yaml
- helm/templates/role-reader.yaml
- helm/templates/role-writer.yaml
- helm/values.yaml
> release artifacts for release v0.0.3

- helm/Chart.yaml
- helm/values.yaml
> release artifacts for release v0.0.4

- config/iam/recommended-policy-arn
Fixes https://github.com/aws-controllers-k8s/community/issues/902 for rds-controller
Add the RDS full access policy as the recommended policy ARN for rds-controller
> Add recommended policy ARN

- helm/Chart.yaml
- helm/values.yaml
> release artifacts for release v0.6.0

- helm/Chart.yaml
- helm/values.yaml
Reverts aws-controllers-k8s/rds-controller#30
> Revert "release artifacts for release v0.6.0"

- helm/Chart.yaml
- helm/values.yaml
> release artifacts for release v0.0.6

- helm/Chart.yaml
- helm/values.yaml
> release artifacts for release v0.0.7

- helm/Chart.yaml
- helm/values.yaml
Adds the new `GlobalCluster` object
> release artifacts for release `v0.0.8`

- helm/Chart.yaml
- helm/values.yaml
> release artifacts for release v0.0.10

- helm/Chart.yaml
- helm/values.yaml
> Release artifacts for v0.0.11

- README.md
This adds additional details for how to deploy the ACK service controller for RDS, including examples for creating database instances using the PostgreSQL and MariaDB engines.
> Add additional setup instructions to README

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1258
* release artifacts for v0.0.24
> release artifacts for v0.0.24

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/generator.yaml
- generator.yaml
- pkg/resource/db_subnet_group/delta.go
- pkg/resource/db_subnet_group/hooks.go
- pkg/resource/db_subnet_group/sdk.go
- templates/hooks/db_subnet_group/delta_pre_compare.go.tpl
- templates/hooks/db_subnet_group/sdk_read_many_post_set_output.go.tpl
- templates/hooks/db_subnet_group/sdk_update_pre_set_output.go.tpl
- test/e2e/db_subnet_group.py
- test/e2e/resources/db_subnet_group_2az.yaml
- test/e2e/tests/test_db_subnet_group.py
Adds support for tagging and updating DBSubnetGroup resources.
Issue aws-controllers-k8s/community#1276
> support tag updates for DBSubnetGroup resources

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Release artificates for v0.0.26
> v0.0.26 release

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Issue #, if available: N/A
Description of changes: v0.0.28 release
> v0.0.28 release

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/templates/deployment.yaml
- helm/values.yaml
Description of changes: v0.0.30 release
> v0.0.30 release

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/db_instance.go
- apis/v1alpha1/generator.yaml
- apis/v1alpha1/types.go
- apis/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/rds.services.k8s.aws_dbinstances.yaml
- generator.yaml
- helm/crds/rds.services.k8s.aws_dbinstances.yaml
- pkg/resource/db_cluster/delta.go
- pkg/resource/db_cluster_parameter_group/delta.go
- pkg/resource/db_instance/delta.go
- pkg/resource/db_instance/hooks.go
- pkg/resource/db_instance/sdk.go
- pkg/resource/db_parameter_group/delta.go
- pkg/resource/db_subnet_group/delta.go
- templates/hooks/db_instance/delta_pre_compare.go.tpl
- templates/hooks/db_instance/sdk_read_many_post_set_output.go.tpl
- templates/hooks/db_instance/sdk_update_pre_build_request.go.tpl
- test/e2e/db_instance.py
- test/e2e/resources/db_instance_postgres14_t3_micro.yaml
- test/e2e/tests/test_db_instance.py
Adds support for updating Tags on a DBInstance resource.
Issue: aws-controllers-k8s/community#1276
> support tag updates for DBInstance

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> release artifacts for release v1.1.2

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/crds/services.k8s.aws_adoptedresources.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Release artifact for release `v1.1.4`
> Release artifact for release `v1.1.4`

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/templates/deployment.yaml
- helm/values.yaml
> release artifacts for release v1.1.8

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Release artifact for release v1.2.0

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Release artifact for release v1.2.1

- pkg/resource/db_cluster/custom_update.go
> Validate autoMinorVersionUpgrade value in spec

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Release artifact for release v1.2.3

- test/e2e/tests/test_db_cluster.py
> Fix dbcluster `CloudWatchLogExport` flaky e2e tests

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Release artifacts for release `v1.4.0`

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Release artifacts for release v1.4.1

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/crds/rds.services.k8s.aws_dbclusterparametergroups.yaml
- helm/crds/rds.services.k8s.aws_dbclusters.yaml
- helm/crds/rds.services.k8s.aws_dbclustersnapshots.yaml
- helm/crds/rds.services.k8s.aws_dbinstances.yaml
- helm/crds/rds.services.k8s.aws_dbparametergroups.yaml
- helm/crds/rds.services.k8s.aws_dbproxies.yaml
- helm/crds/rds.services.k8s.aws_dbsnapshots.yaml
- helm/crds/rds.services.k8s.aws_dbsubnetgroups.yaml
- helm/crds/rds.services.k8s.aws_globalclusters.yaml
- helm/crds/services.k8s.aws_adoptedresources.yaml
- helm/crds/services.k8s.aws_fieldexports.yaml
- helm/templates/NOTES.txt
- helm/templates/_helpers.tpl
- helm/templates/deployment.yaml
- helm/values.yaml
- Generate release artifacts for v1.4.5
> Generate artifacts for v1.4.5

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Generate release artifacts for v1.4.13

- apis/v1alpha1/ack-generate-metadata.yaml
- apis/v1alpha1/generator.yaml
- generator.yaml
- pkg/resource/db_cluster/custom_update.go
- pkg/resource/db_cluster/sdk.go
- add `storageType` to customUpdate
- add terminal error, `storageType` can only be changed once in 30 days.
> add storagetype to customupdate, add terminal error

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Generate release artifacts for v1.4.14

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Release artifacts for release v1.4.16

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Release artifacts for release v1.5.0

- apis/v1alpha1/ack-generate-metadata.yaml
- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Issue #, if available: Fixes [2512](https://github.com/aws-controllers-k8s/community/issues/2512)
> Release artifacts for release v1.4.22

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
fixes https://github.com/aws-controllers-k8s/community/issues/1847
- https://github.com/aws-controllers-k8s/community/issues/1847
> Release artifacts for release v1.4.26

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
Issue #, if available: Fixes [2511](https://github.com/aws-controllers-k8s/community/issues/2511)
> Release artifacts for release v1.6.0

- go.mod
- go.sum
> Pin Runtime to v0.52.0

- config/controller/kustomization.yaml
- helm/Chart.yaml
- helm/templates/NOTES.txt
- helm/values.yaml
> Release artifacts for release v1.6.2
