apis/v1alpha1/db_subnet_group.go
config/crd/bases/rds.services.k8s.aws_dbsubnetgroups.yaml

Brings in changes that include docstring generation for CRD fields.

re-generate with ACK code-gen 0.0.6

---

pkg/resource/db_instance/conditions.go

Fixes the custom setTerminalCondition() function in
pkg/resource/db_instance/conditions.go to fetch the terminal condition
and not the resource synced condition.
Issue aws-controllers-k8s/community#827

fix: setTerminalCondition setting Synced condition

---

apis/v1alpha1/ack-generate-metadata.yaml
go.mod
go.sum
pkg/resource/db_instance/manager.go
pkg/resource/db_instance/manager_factory.go
pkg/resource/db_instance/resource.go
pkg/resource/db_instance/sdk.go
pkg/resource/db_parameter_group/manager.go
pkg/resource/db_parameter_group/manager_factory.go
pkg/resource/db_parameter_group/resource.go
pkg/resource/db_parameter_group/sdk.go
pkg/resource/db_security_group/manager.go
pkg/resource/db_security_group/manager_factory.go
pkg/resource/db_security_group/resource.go
pkg/resource/db_security_group/sdk.go
pkg/resource/db_subnet_group/manager.go
pkg/resource/db_subnet_group/manager_factory.go
pkg/resource/db_subnet_group/resource.go
pkg/resource/db_subnet_group/sdk.go

Regenerates the RDS controller with ACK code-generator v0.3.1, which
brings in ACK runtime v0.3.0 improvements and features.

bring rds-controller up to ACK runtime v0.3.0

---

apis/v1alpha1/ack-generate-metadata.yaml
go.mod
go.sum
pkg/resource/db_cluster/manager.go
pkg/resource/db_cluster/sdk.go
pkg/resource/db_cluster_parameter_group/manager.go
pkg/resource/db_cluster_parameter_group/sdk.go
pkg/resource/db_instance/manager.go
pkg/resource/db_instance/sdk.go
pkg/resource/db_parameter_group/manager.go
pkg/resource/db_parameter_group/sdk.go
pkg/resource/db_security_group/manager.go
pkg/resource/db_security_group/sdk.go
pkg/resource/db_subnet_group/manager.go
pkg/resource/db_subnet_group/sdk.go
templates/hooks/db_cluster/sdk_delete_pre_build_request.go.tpl
templates/hooks/db_instance/sdk_delete_pre_build_request.go.tpl

Brings in ACK runtime 0.6.0 and makes the requisite changes to the
delete sdk hook templates to deal with the altered Delete method
signature.

update to ACK runtime 0.6.0

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_cluster/sdk.go
pkg/resource/db_instance/sdk.go
test/e2e/resources/db_cluster_mysql_serverless.yaml
test/e2e/resources/db_instance_postgres13_t3_micro.yaml
test/e2e/tests/test_db_cluster.py
test/e2e/tests/test_db_instance.py

Sets the ApplyImmediately field in the ModifyDBInstance and
ModifyDBCluster API Input shapes to always be `true`, enabling immediate
modification of the DB cluster or instance.
Issue aws-controllers-k8s/community#865

always ApplyImmediately for DBCluster/Instance

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_instance/hooks.go
pkg/resource/db_instance/sdk.go
templates/hooks/db_instance/sdk_create_post_set_output.go.tpl
templates/hooks/db_instance/sdk_read_many_post_set_output.go.tpl
test/e2e/tests/test_db_instance.py

After creating a new DBInstance resource, we were not setting
ConditionTypeResourceSynced on the resource nor were we asking to
requeue the resource after some time. This meant that the resource's
Status was not being updated on the Kubernetes side, even after the DB
instance's status transitioned to 'available' on the RDS side.
In this patch, we're adding two generic hook implementations for
sdk_read_many_post_set_output and sdk_create_post_set_output that will
create a ConditionTypeResourceSynced on the resource with a value of
ConditionFalse (because the resource isn't actually synced yet).  This
causes the controller to queue the resource up for a new reconciliation
loop, during which the resource's Status will be updated to the latest
observed values.
Fixes Issue …

requeue db instance while not available

---

test/e2e/db_cluster.py
test/e2e/fixtures.py
test/e2e/tests/test_db_cluster.py
test/e2e/tests/test_db_instance.py

This PR includes two patches that provide enhancements and
simplifications to the e2e testing for the RDS controller.
The first enhancement is to separate the Kubernetes secret creation
and management into a pytest fixture that is importable from the
test modules.
The second enhancement pulls the waiter and getter functionality for
DB clusters out of the test module and into a separate importable module.
This will be important for later patches where I need to test *both* DB
cluster and DB instances in the same file and don't want to copy/paste a
bunch of boilerplate waiter/getter code between test modules.

refinement of e2e tests

---

test/e2e/db_instance.py
test/e2e/tests/test_db_cluster.py
test/e2e/tests/test_db_instance.py

Pulls out the waiter and getter functions for DB instance resources into
a test/e2e/db_instance.py file, modeled after the same set of functions
for the DB cluster resource.

refactor DB instance e2e tests

---

generator.yaml
pkg/resource/db_cluster/sdk.go
pkg/resource/db_instance/manager.go
pkg/resource/db_instance/sdk.go
templates/hooks/db_cluster/sdk_read_many_post_set_output.go.tpl
templates/hooks/db_instance/sdk_read_many_post_set_output.go.tpl
templates/hooks/db_instance/sdk_update_pre_build_request.go.tpl
test/e2e/condition.py
test/e2e/tests/test_db_cluster.py
test/e2e/tests/test_db_instance.py

Adds tests that the ACK.ResourceSynced Condition is present on resources
of kind DBCluster and DBInstance and that the status of those conditions
are either False or True depending on the expected state transition of
the DB instance or cluster.
This involved creating some helper functions in test/e2e/condition.py
that assert that a Condition of a specific type and status is present in
a resource's Status.Conditions collection.
In grep'ing through logs for the rds-controller, I noticed that the
AvailabilityZone field for the DBInstance should be late-initialized and
so added that to the generator.yaml file.
Finally, found that ACK.ResourceSynced/True was not being set on
DBCluster and DBInstance resources when the status of the instance or
cluster made its way to 'available'. I added an …

Ensure Synced Condition on DB instance/cluster

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/global_cluster/sdk.go

Issue #, if available: aws-controllers-k8s/community#1027
Remove `DBClusterNotFoundFault` as a terminal condition for `GlobalCluster`.

Remove DBClusterNotFoundFault as a terminal condition for GlobalCluster.

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/db_instance.go
apis/v1alpha1/generator.yaml
apis/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/rds.services.k8s.aws_dbinstances.yaml
generator.yaml
go.mod
go.sum
helm/crds/rds.services.k8s.aws_dbinstances.yaml
pkg/resource/db_cluster/sdk.go
pkg/resource/db_cluster_parameter_group/sdk.go
pkg/resource/db_instance/delta.go
pkg/resource/db_instance/manager.go
pkg/resource/db_instance/sdk.go
pkg/resource/db_parameter_group/sdk.go
pkg/resource/db_security_group/sdk.go
pkg/resource/db_subnet_group/sdk.go
pkg/resource/global_cluster/sdk.go

Regenerates the rds-controller with the latest v0.15.2 runtime.
**BREAKING CHANGES**:
The DBInstance's Spec.DBSecurityGroupNames field is now renamed to just
Spec.DBSecurityGroups. It continues to be a `[]*string` field but now
the rds-controller correctly handles comparisons for this fields value
with the returned latest observed state.
Includes changes to the generator.yaml file that instructs the
code-generator how to handle the DBSecurityGroups field on DBInstance.

Bring in ACK runtime v0.15.2

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_cluster/sdk.go
pkg/resource/db_instance/sdk.go
pkg/resource/global_cluster/sdk.go

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1151
* Remove *InvalidDBClusterStateFault*, *InvalidDBInstanceStateFault*, *InvalidDBInstanceState* and *InvalidVPCNetworkStateFault* from Terminal Exception codes
* All these errors are recoverable and putting them in terminal state code causes reconciliation to stop in valid cases like deleting DBCluster and DBInstances together. When DBInstances eventually get deleted, the DeleteDBCluster call stops returning InvalidDBClusterStateFault as per [troubleshoot guide](https://aws.amazon.com/premiumsupport/knowledge-center/rds-error-delete-aurora-cluster/)
* If there are specific cases where these errors will need to enforce Terminal State, custom hooks can be used in future.
-------
* For …

Update terminal exception code to not include recoverable states

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/db_cluster.go
apis/v1alpha1/db_instance.go
apis/v1alpha1/generator.yaml
apis/v1alpha1/zz_generated.deepcopy.go
cmd/controller/main.go
config/crd/bases/rds.services.k8s.aws_dbclusters.yaml
config/crd/bases/rds.services.k8s.aws_dbinstances.yaml
config/rbac/cluster-role-controller.yaml
generator.yaml
go.mod
go.sum
helm/crds/rds.services.k8s.aws_dbclusters.yaml
helm/crds/rds.services.k8s.aws_dbinstances.yaml
helm/templates/cluster-role-controller.yaml
pkg/resource/db_cluster/delta.go
pkg/resource/db_cluster/references.go
pkg/resource/db_instance/delta.go
pkg/resource/db_instance/references.go

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1258
* Add reference for KMSKey inside DBCluster and DBInstance crds
* Currently there is no support to test cross-controller resource reference. Once https://github.com/aws-controllers-k8s/community/issues/1266 is resolved, I will add automated e2e tests
* I manually tested the referencing KMSKey inside DBInstance works as expected.

add KMSKeyRef inside DBCluster and DBInstance

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_parameter_group/delta.go
pkg/resource/db_parameter_group/hooks.go
pkg/resource/db_parameter_group/sdk.go
templates/hooks/db_parameter_group/delta_pre_compare.go.tpl
templates/hooks/db_parameter_group/sdk_read_many_post_set_output.go.tpl
test/e2e/db_parameter_group.py
test/e2e/resources/db_parameter_group_postgres13_standard.yaml
test/e2e/tests/test_db_parameter_group.py

Adds custom update code to the DBParameterGroup resource manager for
syncing tags. Removes the non-working existing update code in favor of a
`customUpdate` method that only syncs tags.
Issue aws-controllers-k8s/community#1276

support updating tags for DB Parameter Groups

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_cluster_parameter_group/delta.go
pkg/resource/db_cluster_parameter_group/hooks.go
pkg/resource/db_cluster_parameter_group/sdk.go
templates/hooks/db_cluster_parameter_group/delta_pre_compare.go.tpl
templates/hooks/db_cluster_parameter_group/sdk_read_many_post_set_output.go.tpl
test/e2e/db_cluster_parameter_group.py
test/e2e/db_parameter_group.py
test/e2e/resources/db_cluster_parameter_group_aurora_mysql5.7.yaml
test/e2e/tests/test_db_cluster_parameter_group.py
test/e2e/tests/test_db_parameter_group.py

Adds support for updating and retrieving tags for DB cluster parameter
groups.
Issue aws-controllers-k8s/community#1276

support updating tags on DB cluster param groups

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/db_instance.go
apis/v1alpha1/generator.yaml
apis/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/rds.services.k8s.aws_dbinstances.yaml
generator.yaml
helm/crds/rds.services.k8s.aws_dbinstances.yaml
pkg/resource/db_instance/delta.go
pkg/resource/db_instance/sdk.go

Fixes https://github.com/aws-controllers-k8s/community/issues/1251
Rename EnablePerformanceInsights to PerformanceInsightsEnabled for RDS API CreateDBInstance and ModifyDBInstance to avoid conflict with DecribeDBInstance PerformanceInsightsEnabled status
Rename EnablePerformanceInsights to PerformanceInsightsEnabled for RDS API CreateDBInstance and ModifyDBInstance to avoid conflict with DecribeDBInstance PerformanceInsightsEnabled status
1. make the change in generator.yaml file to rename EnablePerformanceInsights to PerformanceInsightsEnabled
2. run existing rds controller test and passed 

Rename EnablePerformanceInsights to PerformanceInsightsEnabled for CreateDBInstance and ModifyDBInstance api

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
apis/v1alpha1/types.go
apis/v1alpha1/zz_generated.deepcopy.go
generator.yaml
pkg/resource/db_instance/sdk.go

Issue #, if available:[ issue-1138 ](https://github.com/aws-controllers-k8s/community/issues/1138)
Add is_immutable = true for AvailabilityZone in DBInstance CRD. AvailabilityZone is not able to be changed after db instance is created. 

Add immutable tag to AvailabilityZone in DBInstance

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_cluster/custom_update.go
pkg/resource/db_instance/sdk.go

Fixes aws-controllers-k8s/community#1265
https://github.com/aws-controllers-k8s/community/issues/1265
This PR is setting AllowMajorVersionUpgrade to true for both modify db instance and modify db cluster.
This flag was designed as protect flag to avoid accidentally engine version upgrade, however this is not necessary for controller side. whenever customer make change to engine version, ACK controller should take instance to target engine version. 

Allow major version upgrade by setting AllowMajorVersionUpgrade to true

---

apis/v1alpha1/ack-generate-metadata.yaml
pkg/resource/db_instance/sdk.go
templates/hooks/db_instance/sdk_update_post_build_request.go.tpl

This is the reason why rds instance has unnecessary modify workflows for now.
instance will have action of `reset_master_pwd`, r`otate_credential` and `config_enhanced_monitoring` whenever an unrelated param get updated.  RDS side doesn't compare diff of these params and trigger workflow anyway which is pretty annoying and increase sync/wait time. 
- MonitoringInterval -> cause new config_enhanced_monitoring action
- CACertificateIdentifier -> cause rotate_credential action
- MasterUserPassword -> cause reset_master_pwd action 
We first check whether input has delta or not, if not, we don't put it inside rds modify db instance request. If it has delta, it's added into modify request. 
Tested by flipping `CopyTagsToSnapshot` filed and not see …

Ignore several fields for rds modify call when no delta in yaml file

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_cluster/sdk.go
pkg/resource/db_instance/sdk.go

Remove DBParameterGroupNotFound and DBSubnetGroupNotFoundFault from terminal exception
https://github.com/aws-controllers-k8s/community/issues/1257
Since `DBParameterGroup` and `DBSubnetGroup` are resource can be created by controller, controller should retry create `dbinstance/dbcluster` when these resource are created and available in k8s.
Remove them from terminal code so controller can keep retrying. 
Tested by create instance with new db subnet group/param group, and validated controller keep retrying creating and create successfully when new subnet group/param group created in k8s.

Remove DBParameterGroupNotFound and DBSubnetGroupNotFoundFault from terminal exception

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_parameter_group/sdk.go
pkg/resource/db_subnet_group/sdk.go

https://github.com/aws-controllers-k8s/community/issues/1264
issue-1264 was due to `DBParameterGroupFamily` is not renamed to` Family` for `DescribeDBParameterGroups` operation. 
Adding corresponding rename so AdoptedResource of db param group can work. 
basically create and read `DBParameterGroup`/`DBSubnetGroup` operations should have same rename strategy, hence align all of them here  
Previous error is: 
```
1.6553342486477876e+09	ERROR	controller.adoptedresource	Reconciler error	{"reconciler group": "services.k8s.aws", "reconciler kind": "AdoptedResource", "name": "brucegu-ack-pg-1", "namespace": "default", "error": "DBParameterGroup.rds.services.k8s.aws \"brucegu-ack-pg-1\" is invalid: spec.family: Required value"}
```
After this …

Fix rename of DBParameterGroup family for AdoptedResource

---

apis/v1alpha1/ack-generate-metadata.yaml
pkg/resource/db_instance/delta.go
pkg/resource/db_instance/hooks.go
pkg/resource/db_instance/sdk.go
templates/hooks/db_instance/delta_pre_compare.go.tpl
templates/hooks/db_instance/sdk_update_post_build_request.go.tpl

no issue number 
2 changes in this pr
1. ignore NetworkType param when no delta found. RDS coral service will accept request when param has NetworkType param and trigger workflow, although inside rds workflow, it will do noop. it's still not best experience for customer since instance will leave active/none state when this happen.  (this is introduced recently by updating rds api version)
3. RDS will choose preferred engine minor version when only major version give. controller should not try to take them as different and try to sync them. e.g. spec has `14`, rds status shows `14.1`, they should be treated same. Before this fix, controller is trying to sync them forever.  Previous error log: 
```
1.6557458184530575e+09	INFO	ackrt	desired …
```

Ignore NetworkType param if no change, not consider diff when engine version diff in minor version

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/db_cluster.go
apis/v1alpha1/generator.yaml
apis/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/rds.services.k8s.aws_dbclusters.yaml
generator.yaml
helm/crds/rds.services.k8s.aws_dbclusters.yaml
pkg/resource/db_cluster/custom_update.go
pkg/resource/db_cluster/delta.go
pkg/resource/db_cluster/sdk.go
pkg/resource/db_cluster_parameter_group/sdk.go
pkg/resource/db_instance/sdk.go
pkg/resource/db_parameter_group/sdk.go
pkg/resource/db_subnet_group/sdk.go
pkg/resource/global_cluster/sdk.go

https://github.com/aws-controllers-k8s/community/issues/1373
2 changes here + auto build which takes latest runtime changes in rds
1.  rename the scalingConfiguration to scalingConfigurationInfo in Create/ModifyDBClusterInput, so it only appear in Spec instead of Status of cluster.
2. fix issue of 1373, it is due to we currently still use custom update logic, and need update it based on rds api update.  see [pkg/resource/db_cluster/custom_update.go](https://github.com/aws-controllers-k8s/rds-controller/compare/main...brucegucode:rds-controller:issue-1373?expand=1#diff-1f439d0df6b144c73ac51eff110e99fe2262d68871d881f6c6eda8db5bfbe9b1) for detail 
Testing:
Verified by updating serverlessV2ScalingConfiguration minCap or maxCap and verified it got …

Add DBCluster serverlessV2ScalingConfiguration update support

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/db_cluster.go
apis/v1alpha1/db_instance.go
apis/v1alpha1/generator.yaml
apis/v1alpha1/zz_generated.deepcopy.go
cmd/controller/main.go
config/crd/bases/rds.services.k8s.aws_dbclusters.yaml
config/crd/bases/rds.services.k8s.aws_dbinstances.yaml
config/rbac/cluster-role-controller.yaml
generator.yaml
go.mod
go.sum
helm/crds/rds.services.k8s.aws_dbclusters.yaml
helm/crds/rds.services.k8s.aws_dbinstances.yaml
helm/templates/cluster-role-controller.yaml
pkg/resource/db_cluster/delta.go
pkg/resource/db_cluster/references.go
pkg/resource/db_instance/delta.go
pkg/resource/db_instance/references.go

https://github.com/aws-controllers-k8s/community/issues/1378
Add reference for DBInstance/Cluster ParameterGroup/SubnetGroup/vpcSecurityGroup. 
Here is my testing process, it should apply to param group and vpc security group too. 
1. Try create a rds instance `brucegu-test-ref-4` and specify 
```  
dbSubnetGroupRef:
from:
name: "brucegu-test-subnet-11""
```
but no `brucegu-test-subnet-11` is available yet. 
2. Verify db instance state has 
```
Message:               dbsubnetgroups.rds.services.k8s.aws "brucegu-test-subnet-11" not found
Status:                Unknown
Type:                  ACK.ReferencesResolved
```
3. Create db SubnetGroup  `brucegu-test-subnet-11` from SubnetGroup CRD 
4. Verify db instance `brucegu-test-ref-4` is created …

Add reference for db instance/cluster param/subnet/vpcsecurity group

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_cluster_parameter_group/sdk.go
pkg/resource/db_instance/sdk.go
pkg/resource/db_subnet_group/sdk.go
templates/hooks/db_subnet_group/sdk_read_many_post_set_output.go.tpl

https://github.com/aws-controllers-k8s/community/issues/1389
Fix issue of adopted resource for both DBClusterParameterGroup and DBSubnetGroup
1. for DBClusterParameterGroup, it's due to the rename issue that `DBParameterGroupFamily` need be called `Family` and `DBClusterParameterGroupName` need be called `Name`
2. for DBSubnetGroup, synced with @RedbackThomson , it's due to rds output status of `DBSubnetGroup` doesn't have `SubnetIDs`, and it only has `Subnets. SubnetIdentifier`, so we need to use hook to append each of them. 
With these above fixed, adopted resource should work for all available RDS CRDs now. 

Fix issue of adopted resource for both DBClusterParameterGroup and DBSubnetGroup

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/db_cluster.go
apis/v1alpha1/generator.yaml
apis/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/rds.services.k8s.aws_dbclusters.yaml
generator.yaml
helm/crds/rds.services.k8s.aws_dbclusters.yaml
helm/values.schema.json
pkg/resource/db_cluster/delta.go
pkg/resource/db_cluster/hooks.go
pkg/resource/db_cluster/sdk.go
templates/hooks/db_cluster/sdk_create_pre_build_request.go.tpl
templates/hooks/db_cluster/sdk_file_end.go.tpl

https://github.com/aws-controllers-k8s/community/issues/1390
It's similar to what we did in https://github.com/aws-controllers-k8s/rds-controller/pull/78 
This PR will enable restore db cluster from snapshot, either dbSnapshot or dbClusterSnapshot. 
Fixed the issue during testing and verified it can work with both cluster snapshot and db instance snapshot. Controller can issue restore db cluster from snapshot API and resource is synced after creation succeed.  
For cluster snapshot restore to db cluster: 
```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBCluster
metadata:
name: "brucegu-restore-0"
spec:
backupRetentionPeriod: 1
dbClusterIdentifier: brucegu-restore-0
engine: aurora-postgresql
engineVersion: "13.7"
snapshotIdentifier: …
```

Allow restore db snapshot from snapshot 

---

test/e2e/bootstrap_resources.py
test/e2e/replacement_values.py
test/e2e/requirements.txt
test/e2e/resources/db_instance_postgres14_t3_micro.yaml
test/e2e/resources/db_subnet_group_2az.yaml
test/e2e/service_bootstrap.py
test/e2e/service_cleanup.py
test/e2e/tests/test_db_cluster.py
test/e2e/tests/test_db_cluster_parameter_group.py
test/e2e/tests/test_db_instance.py
test/e2e/tests/test_db_parameter_group.py
test/e2e/tests/test_db_subnet_group.py

https://github.com/aws-controllers-k8s/community/issues/1325
This is the first part of using new bootstrap logic for bootstrap shared source for rds e2e tests, VPC/Subnet here. 
I'm expecting to have a new pr for adding bootstrap for rds specific resource later. 
1. use new bootstrap logic to create VPC and subnet are created within VPC as subResource
2. Remove creation of `dbSubnetGroup` since we can rely on rds api to create default `dbSubnetGroup` if no specified and it's not needed to validate that logic in the controller itself. 
3. Not too much change on the e2e test itself, it's still using `load_rds_resource` call to create resource. We can think of bootstraping rds resource later. 
(I'm not very confident with this pr, but tests seem …

Use new bootstrap logic for shared resource like VPC for rds controller tests

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_instance/delta.go
pkg/resource/db_instance/hooks.go
pkg/resource/db_instance/sdk.go
templates/hooks/db_instance/delta_pre_compare.go.tpl
test/e2e/tests/test_db_instance.py

In PR #95, we added a `customPreCompare` function to
`pkg/resource/db_instance/hooks.go` and changed the `generator.yaml` to
use a code snippet instead of the
`templates/hooks/db_instance/delta_pre_compare.go.tpl` template file.
However, we did not delete the
`templates/hooks/db_instance/delta_pre_compare.go.tpl` file and when I
went to do the updating DB instance tags patch, nobody noticed that I
had added a call to `compareTags` into the (now-unused) template file.
This meant that `compareTags` is never called which means changes to
tags were not being properly on DBInstance resources.
This patch moves all the custom code for delta pre-checks back into the
template file and gets rid of the custom code snippet in generator.yaml,
consolidating all this logic into the template file.
Issue: …

correct delta_pre_compare for DBInstance

---

pkg/resource/db_instance/hooks.go

This patch modifies the tags comparison functions to fix a bug that was
recently observed in prow e2e tests.
- Fixes `computeTagsDelta` function for `pkg/db_instance/hooks.go`

Fix `computeTagsDelta` function

---

test/e2e/tests/test_db_instance.py

update e2e test to avoid 2nd change of multiaz flag, due to 
https://github.com/aws-controllers-k8s/community/issues/1376 

Comment out last multiAZ flag assert

---

pkg/resource/db_cluster/hooks.go
pkg/resource/db_cluster_parameter_group/hooks.go
pkg/resource/db_instance/hooks.go
pkg/resource/db_parameter_group/hooks.go
pkg/resource/db_subnet_group/hooks.go
pkg/util/tags.go
pkg/util/tags_test.go

This patch updates the `computeTagsDelta` function for `db_cluster`,
`db_parameter_group`, `db_subnet_group` and `db_cluster_parameter_group`
The previous implementation always returned a non-empty `toAdd` array
which causes the controller to make unnecessary `TagResource` API Calls.
Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>

Update `computeTagsDelta` function

---

apis/v1alpha1/ack-generate-metadata.yaml
pkg/resource/db_proxy/hooks.go
test/e2e/bootstrap_resources.py
test/e2e/db_proxy.py
test/e2e/resources/db_proxy.yaml
test/e2e/service_bootstrap.py
test/e2e/tests/test_db_proxy.py

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1440
- Add e2e test for rds `dbproxy` resource
Two major issues were observed while testing locally
1. This test needs a complex dependency chain and it will cause bootstrap logic pretty complex. I'm inclined to either hard code it for our rds tests account or we just remove it for now.  The dependency chain is like this :  create one base rds instance -> create one aws secret service for this rds instance -> create an iam role for this secret -> create rds proxy using iam role & secret . Deletion is the opposite way.  Currently we're not able to create a rds instance in bootstrap logic or create a aws secret service secret. 
2. The e2e test lasts pretty long. creation will take around …

Add e2e test for rdsproxy

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/db_parameter_group.go
apis/v1alpha1/generator.yaml
apis/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/rds.services.k8s.aws_dbparametergroups.yaml
generator.yaml
helm/crds/rds.services.k8s.aws_dbparametergroups.yaml
pkg/resource/db_parameter_group/delta.go
pkg/resource/db_parameter_group/hooks.go
pkg/resource/db_parameter_group/sdk.go
templates/hooks/db_parameter_group/sdk_create_post_set_output.go.tpl
templates/hooks/db_parameter_group/sdk_read_many_post_set_output.go.tpl
test/e2e/db_parameter_group.py
test/e2e/resources/db_parameter_group_postgres13_standard.yaml
test/e2e/tests/test_db_parameter_group.py

Adds code to allow a user to specify a set of parameter override values
for a DB parameter group.
The `Spec.ParameterOverrides` is a `map[string]*string` containing the
parameter names and values for parameters in a DB parameter group that
the user wishes to override from their defaults.
The `Status.ParameterOverrideStatuses` field is a slice of `Parameter`
structs that contains more "status-y" information about those overridden
parameters.
Still yet to work out is how I'm going to keep track of which parameters
for which DB engine family can have ApplyMethod=intermediate and which
ones must have ApplyMethod=pending-reboot.

support overriding parameter values on param group

---

apis/v1alpha1/ack-generate-metadata.yaml
pkg/resource/db_cluster/sdk.go
pkg/resource/db_instance/sdk.go
templates/hooks/db_cluster/sdk_read_many_post_set_output.go.tpl
templates/hooks/db_instance/sdk_read_many_post_set_output.go.tpl

Issue #, if available: aws-controllers-k8s/community/issues/1712
Because the names of the security group fields returned by the API differ the `VPCSecurityGroupsIDs` is not read from the API response into the _latest_. Instead the values of the _desired_ is copied. This means that the controller determines that there is not need for an update. Instead by copying the the VPCSecurityGroups field from the status into the spec the controller can correctly determine that there is a difference between the latest and desired. This affects both type __DBCluster__ and __DBInstance__.

Copy the security groups from status into spec

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/generator.yaml
generator.yaml
helm/crds/services.k8s.aws_adoptedresources.yaml
pkg/resource/db_proxy/hooks.go
pkg/resource/db_proxy/sdk.go
templates/hooks/db_proxy/sdk_create_post_set_output.go.tpl
templates/hooks/db_proxy/sdk_delete_pre_build_request.go.tpl
templates/hooks/db_proxy/sdk_read_many_post_set_output.go.tpl
templates/hooks/db_proxy/sdk_update_post_set_output.go.tpl
templates/hooks/db_proxy/sdk_update_pre_build_request.go.tpl
test/e2e/.gitignore
test/e2e/conftest.py
test/e2e/tests/test_db_proxy.py

The DBProxy APIs put the resource into `creating` state for ~10 minutes before becoming `available`, as well as `deleting` before it is gone. This PR copies the systems we use for `DBInstance`, which has the same properties, into custom hooks for `DBProxy`. It also updates the tests for `DBProxy` to use proper fixturing and to use a autogenerated resource name suffix (so tests don't collide).

Add asynchronous status checks for `DBProxy`

---

apis/v1alpha1/ack-generate-metadata.yaml
pkg/resource/db_cluster_parameter_group/hooks.go
pkg/resource/db_cluster_parameter_group/sdk.go
pkg/resource/db_parameter_group/hooks.go
pkg/resource/db_parameter_group/sdk.go
templates/hooks/db_cluster_parameter_group/sdk_create_post_set_output.go.tpl
templates/hooks/db_parameter_group/sdk_create_post_set_output.go.tpl
test/e2e/db_cluster.py
test/e2e/db_instance.py
test/e2e/resources/db_cluster_parameter_group_aurora_postgresql14.yaml
test/e2e/resources/db_cluster_ref.yaml
test/e2e/resources/db_instance_ref.yaml
test/e2e/resources/db_parameter_group_aurora_postgresql14.yaml
test/e2e/tests/test_db_cluster_parameter_group.py
test/e2e/tests/test_db_parameter_group.py
test/e2e/tests/test_references.py

This patch fixes both the DB Parameter Group and the DB Cluster Parameter Group resources failure to properly get to ACK.ResourceSynced=True quickly and reliably. I removed the manual requeueWhileCreating condition for both Param Group and Cluster Param Group resources, replacing that sdk_create_post_set_output hook with a call to `syncParameters`, supplying a `nil` `latest` parameter. This allowed the parameter overrides to be immediately set after the parameter group was created.
Added a lengthy e2e test for RDS resource references based on the YAML definitions present in the related issue
(aws-controllers-k8s/community#1727) with a DBCluster resource that references a DB Cluster Parameter Group, a DBInstance resource that references a DB Parameter Group (by AWSResourceReference) and …

ensure all resources sync for RDS

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/db_cluster.go
apis/v1alpha1/db_instance.go
apis/v1alpha1/generator.yaml
apis/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/rds.services.k8s.aws_dbclusters.yaml
config/crd/bases/rds.services.k8s.aws_dbinstances.yaml
generator.yaml
helm/crds/rds.services.k8s.aws_dbclusters.yaml
helm/crds/rds.services.k8s.aws_dbinstances.yaml
pkg/resource/db_cluster/delta.go
pkg/resource/db_cluster/references.go
pkg/resource/db_instance/delta.go
pkg/resource/db_instance/references.go

For DBCluster and DBInstance resources, the MasterUserSecretKMSKeyID field can refer to a KMS Key resource.

Add reference for MasterUserSecretKMSKeyID

---

apis/v1alpha1/ack-generate-metadata.yaml
config/controller/deployment.yaml
helm/crds/services.k8s.aws_adoptedresources.yaml
helm/templates/_helpers.tpl
helm/templates/deployment.yaml
helm/values.schema.json
helm/values.yaml
pkg/resource/db_cluster/resource.go
pkg/resource/db_cluster_parameter_group/resource.go
pkg/resource/db_instance/resource.go
pkg/resource/db_instance/sdk.go
pkg/resource/db_parameter_group/resource.go
pkg/resource/db_proxy/resource.go
pkg/resource/db_subnet_group/resource.go
pkg/resource/global_cluster/resource.go
templates/hooks/db_instance/sdk_read_many_post_set_output.go.tpl
templates/hooks/db_instance/sdk_update_post_set_output.go.tpl
test/e2e/tests/test_db_instance.py

Both ModifyDBInstance and DescribeDBInstances returns a DBInstance struct that contains the *previously set* values for various mutable fields. This is problematic because it causes a "flopping" behaviour when the user has modified a Spec field from value A to value B but the output shape from ModifyDBInstance for that field contains value A, the standard SetOutput Go code generated above will set the Spec field to the *old* value again. The next time the reconciler runs, it will read the latest observed resource, see a difference between the desired and the latest state (that actually does not exist because the difference is comparing the value of the fields before they were changed) and attempt to modify the field from value B to value A again, causing a flop loop.
Luckily, the Output …

prevent DB Instance desired field state flapping

---

apis/v1alpha1/ack-generate-metadata.yaml
pkg/resource/db_cluster/sdk.go
templates/hooks/db_cluster/sdk_read_many_post_set_output.go.tpl
test/e2e/db_cluster.py
test/e2e/resources/db_cluster_aurora_postgres.yaml
test/e2e/tests/test_db_cluster.py

Issue #, if available: #1937
Description of changes: Like the parameter groups the IAM authentication flag has different names in the input and output to the API. A hook is need to correctly set the value.

Copy IAM authentication state from status

---

pkg/resource/db_cluster/custom_update.go

Fixes [Issue](https://github.com/aws-controllers-k8s/community/issues/2009)

Ignore EngineVersion minor updates when `autoMinorVersionUpgrade` is enabled

---

apis/v1alpha1/ack-generate-metadata.yaml
apis/v1alpha1/annotation.go
apis/v1alpha1/generator.yaml
generator.yaml
pkg/resource/db_cluster/hooks.go
pkg/resource/db_cluster/sdk.go
pkg/resource/db_instance/hooks.go
pkg/resource/db_instance/sdk.go
pkg/util/annotations.go
pkg/util/annotations_test.go
templates/hooks/db_cluster/sdk_delete_post_build_request.go.tpl
templates/hooks/db_instance/sdk_delete_post_build_request.go.tpl

This commit adds support for configuring delete options for DBInstances
and DBclusters via resource annotations:
- `SkipFinalSnapshot` (default: true): Skip taking a final snapshot
before deletion
- `FinalDBSnapshotIdentifier`: Specify the identifier of the final
snapshot
- `DeleteAutomatedBackups` (default: true): Delete automated backups
associated with the instance/cluster
The generator config is updated to use `sdk_delete_post_build_request`
hook which parses the annotations and set the appropriate fields on
`DeleteDBInstanceInput` and `DeleteDBClusterInput`.
The default behaviour remains unchanged (skip final snapshot, retain
automated backups), but users can now opt-in to taking a final snapshot
or deleting automatedd backups by setting the corresponding annotations
on the resource. …

Add annotations to configure final snapshot and automated backup deletion

---

README.md

Update `README.md` with documentation for supported annotations on `DBInstance`
and `DBCluster` resources:
- rds.services.k8s.aws/skip-final-snapshot (default: true): Skip creating a
final snapshot before deletion
- rds.services.k8s.aws/final-db-snapshot-identifier: Specify the identifier
to use for the final snapshot
- rds.services.k8s.aws/delete-automated-backups (default: false): Delete
automated backups associated with the instance/cluster

add annotation documentation for `DBInstance` and `DBCluster`

---

apis/v1alpha1/ack-generate-metadata.yaml
pkg/resource/db_cluster/delta.go
templates/hooks/db_cluster/delta_pre_compare.go.tpl

Fixes:
``` When the StorageType parameter for a DBCluster is explicitly set to its default value ("aurora"), the AWS RDS API doesn't return this field in the response. However, when set to a non-default value (like "aurora-iopt1"), the API does return the field. This inconsistency causes problems with the controller's delta comparison logic.```
Modified the `delta_pre_compare` hook to default the StorageType field to "aurora" when it's nil in the latest resource state. This addresses the issue where the AWS RDS API doesn't return the StorageType field when it's set to the default value "aurora".

fix storageType delta

---

apis/v1alpha1/ack-generate-metadata.yaml
pkg/resource/db_subnet_group/sdk.go
templates/hooks/db_subnet_group/sdk_read_many_post_set_output.go.tpl

Issue [#2083](https://github.com/aws-controllers-k8s/community/issues/2083)
In sdkFind hook, the SubnetIDs returned by AWS are appended 
to the latest resource Spec.SubnetIDs. This ended up being an 
issue because the latest resource is a deep copy of desired. 
And there were unnecessary update calls were being made due 
to this issue.
This change ensures the only the SubnetIDs returned by the 
DescribeDBSubnetGroup call are populated in the latest SubnetIDs.

fix: remove SubnetIDs duplicates

---

pkg/resource/db_cluster/custom_update.go

fixes: https://github.com/aws-controllers-k8s/community/issues/2380
When `ModifyDBCluster` is called for an engine version update, the API response might still reflect the *old* version while the update is in progress asynchronously. Previously, we patched `ko` with this potentially outdated version from the response. This caused the next reconciliation to incorrectly see a mismatch between the desired (new) version and the patched (old) version, leading to unnecessary downgrade attempts.
**Fix:**
The `customUpdate` function does not patch `EngineVersion`
**Example:**
1.  **User Spec:** `EngineVersion: "11.0"`
2.  **Current State:** `EngineVersion: "10.0"`
3.  `ModifyDBCluster` is called to update to `11.0`.
4.  **API Response:** (while updating) `EngineVersion: …

Prevent incorrect DB Cluster engine version patching during updates

---

pkg/resource/db_cluster_parameter_group/hooks.go
test/e2e/db_cluster_parameter_group.py
test/e2e/db_parameter_group.py
test/e2e/resources/db_cluster_parameter_group_aurora_mysql8.0_logging.yaml
test/e2e/tests/test_db_cluster_parameter_group.py

fixes https://github.com/aws-controllers-k8s/community/issues/1847
`DbClusterParameterGroup` was incorrectly rejecting valid parameters like `slow_query_log`, `long_query_time`, and `log_queries_not_using_indexes` with "unknown parameter" errors. This occurred because the controller only validated parameters against `DescribeEngineDefaultClusterParameters` API, but some valid cluster parameters (particularly MySQL logging parameters) are only listed in the `DescribeEngineDefaultParameters` (instance-level) API response.
Implemented a fallback parameter validation mechanism in `getParameterMeta()` that first checks cluster-level parameter defaults, and if not found, falls back to instance-level parameter defaults before rejecting a parameter as unknown. This allows …

Implemented a fallback parameter validation for DbClusterParameterGroup
